language: ruby
cache:
  directories:
    - vendor/bundle
    - tmp/cache
bundler_args: --without development --path vendor/bundle
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
