databases:
  - name: ua-books-db
    databaseName: ua_books
    user: ua_books_user

services:
  - type: web
    name: ua-books-web
    region: frankfurt
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ua-books-db
          property: connectionString
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: SECRET_KEY_BASE
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: RAILS_ADMIN_NAME
        sync: false
      - key: RAILS_ADMIN_PASSWORD
        sync: false
