version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2 
jobs:
  test:
    docker:
      - image: cimg/ruby:2.6-node
      - environment:
          POSTGRES_DB: ua_books_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: circleci-ruby
        image: 'circleci/postgres:9.6-alpine'
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: circleci-ruby
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:structure:load --trace'
          name: Database setup
      - ruby/rspec-test
workflows:
  main:
    jobs:
      - test
