default: &default
  public_key: 10b871ebc0271ab7d9ad
  secret_key: not provided

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  public_key: <%= ENV["UPLOADCARE_PUBLIC_KEY"] %>
  secret_key: <%= ENV["UPLOADCARE_SECRET_KEY"] %>
